# Generated by Django 6.1.1 on 2026-09-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('operating_hours', models.CharField(default='24/7', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_label', models.CharField(max_length=50)),
                ('connector_type', models.CharField(choices=[('Type1', 'Type 1'), ('Type2', 'Type 2'), ('CCS', 'CCS'), ('CHAdeMO', 'CHAdeMO')], max_length=20)),
                ('power_kw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='stations.chargingstation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
